### ISSUE TITLE
Update nodemailer to support node 0.12

### ISSUE THREAD

**Issue by gzurbach** [RGBboy/express-mailer#18]
I just updated node from 0.10 to 0.12 and it seems to be breaking express-mailer. According to this issue (https://github.com/andris9/Nodemailer/issues/391) it seems that only nodemailer 1.3.2 supports Node 0.12 and io.js. Is there a plan to upgrade nodemailer soon?

**Comment by RGBboy** [comment]
To be honest I rarely use this module and it serves my purpose with node 0.10. I would recommend using nodemailer directly if that is what you need. I welcome collaboration and pull requests if you would like to contribute here.

**Comment by gzurbach** [comment]
Thanks for your answer! I ended up rewriting everything with nodemailer. It makes more sense, especially if you are not maintaining this library.
