### ISSUE TITLE
rendering an html email does not work

### ISSUE THREAD

**Issue by chaudhry-junaid** [RGBboy/express-mailer#19]
I am using jade templates to render html emails using res.mailer.render:

     res.mailer.render('email', {
        to: 'example@example.com',
        subject: 'Test Email',
        otherProperty: 'Other Property'
      }, function (err, message) {
        if (err) {
          // handle error
          console.log(err);
          res.send('There was an error rendering the email');
          return;
        }
        res.header('Content-Type', 'text/html');
        res.send(message);
      });

This does not render the html properly because html tags contain the chars 3D=22 and =22 which distort the original presentation of the email. This is inconvenient as one actually has to send the email to view the final result of an html email.

**Comment by chaudhry-junaid** [comment]
Note: 
Using mimelib as follows before printing the email works when testing in the browser:
    ...
    var mimelib = require("mimelib");
    message = mimelib.decodeQuotedPrintable(message);
    res.header('Content-Type', 'text/html');
    res.send(message);
    ...

**Comment by RGBboy** [comment]
I think ideally the render function should render the email exactly as it is sent (i.e. with 3D=22 etc) Using mimelib looks like the right solution.

Could you change the content type to an email friendly content type?

**Comment by chaudhry-junaid** [comment]
I tried adding the following: 

    res.header('Content-Transfer-Encoding', 'quoted-printable');

However, 3D=22 etc still appear. Probably web browsers (where I am displaying the rendered email) don't support quoted-printable (yet!)

Could you guide in what to set in the content-type header. I did not yet come across any special value for email. Thank.

**Comment by RGBboy** [comment]
Sorry I think you might have misunderstood. I was not sure if there as a content type that supported this, I just thought there might be one. One thing that I do is render it to a .eml file then open it on my mac to see how it looks.

**Comment by chaudhry-junaid** [comment]
I see. Well mimelib fixed my original issue, so perhaps this can be closed if no additional function need be created. Thanks.
