### ISSUE TITLE
CC and BCC fields not working

### ISSUE THREAD

**Issue by shlomisas** [RGBboy/express-mailer#20]
When adding CC or BCC options it's not sending into node-mailer.

Please add the following lines into lib/express-mailer.js under line 70:

sendOptions.cc = sendOptions.cc || locals.cc;
sendOptions.bcc = sendOptions.bcc || locals.bcc;

Thanks.

**Comment by shlomisas** [comment]
BTW, this is the second bug i found at the same code place (before it was the replyTo field), i think it's better to dynamically merge the both objects (locals and sendOptions) instead of do it manually line by line. this way you'll avoid omitting another available parameters from node-mailer package you wrap.

**Comment by miduga** [comment]
+1

**Comment by RGBboy** [comment]
If you would like to submit a pull request with appropriate tests I will be more than happy to merge it.

**Comment by shlomisas** [comment]
Will do later! Thanks..

**Comment by RGBboy** [comment]
merged and the new version 0.3.0 published
