### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by pagoad** [RGBboy/express-mailer#23]
Hi! I have a problem:

    Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (mypathapp/HTML/dist/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (mypathapp/HTML/dist/node_modules/express/lib/response.js:154:12)
    at mypathapp/HTML/dist/server/controllers/index.js:225:13
    at MailComposer.returnCallback (mypathapp/HTML/dist/node_modules/express-mailer/lib/express-mailer.js:81:11)
    at SMTPConnectionPool._onConnectionReady (mypathapp/HTML/dist/node_modules/express-mailer/node_modules/nodemailer/node_modules/simplesmtp/lib/pool.js:305:39)
    at SMTPClient.emit (events.js:110:17)
    at SMTPClient._actionStream (mypathapp/HTML/dist/node_modules/express-mailer/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:1096:14)
    at SMTPClient._onData (mypathapp/HTML/dist/node_modules/express-mailer/node_modules/nodemailer/node_modules/simplesmtp/lib/client.js:354:29)
    at TLSSocket.emit (events.js:107:17)

Line 225:

    res.send('Email Sent' + req.body.from);

All code:

    res.mailer.send('email', {
        to: 'mail@mail.com',
        subject: 'Subject', // REQUIRED. 
        from: req.body.from,
        mail: req.body.mail,
        phone: req.body.phone,
        message: req.body.message
    }, function(err) {
        if (err) {
            console.log(err);
            res.send('There was an error sending the email');
            return;
        }
        res.send('Email Sent' + req.body.from);
    });

I have no idea what I'm doing wrong.

**Comment by RGBboy** [comment]
I'm guessing you are calling res.send (not mailer.send) somewhere else in your route stack. What does your complete route handler look like?

**Comment by pagoad** [comment]
I do not use res.send anywhere else.
Only in other views. 
res.mailer is first function in this view. After it I have integration with CRM and I don't wont to public it.
But there is no more res.send

**Comment by RGBboy** [comment]
Can you at least show the whole route handler for this route? I might be able to shed some light. 

I'm pretty sure this is not a mailer issue and will be a problem with the way the routes are being handled. Do you call next in this route? You might want to try comment out the res.mailer.send block and try the request again to identify the suspect route.

**Comment by pagoad** [comment]
The whole view:
    

    res.mailer.send('email', {
        to: 'mail@mail.com',
        subject: 'Subject', // REQUIRED. 
        from: req.body.from,
        mail: req.body.mail,
        phone: req.body.phone,
        message: req.body.message
    }, function(err) {
        if (err) {
            console.log(err);
            res.send('There was an error sending the email');
            return;
        }
        res.send('Email Sent' + req.body.from);
    });
    var request = require('request');
    var fields = req.body.from.split(' ');
    var first_name = fields[0];
    if (fields[1] === undefined) {
        var last_name = 'Unnown';
    } else {
        var last_name = fields[1];
    }
    var myhost = req.get('host');

    var options = {
        uri: 'xxxxxxx',
        method: 'POST',
        headers: {
            'User-Agent': 'request',
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": "xxxxxxx"
        },
        useQuerystring: true,
        json: {
            "data": {
                "first_name": first_name,
                "last_name": last_name,
                "organization_name": "xxxxxxx",
                "description": "Contact from:" + myhost,
                "mobile": req.body.phone,
                "email": req.body.mail
            }
        }
    };
    request(options, function(error, response, body) {

        var options = {
            uri: 'xxxxxxx',
            method: 'POST',
            headers: {
                'User-Agent': 'request',
                "Accept": "application/json",
                "Content-Type": "application/json",
                "Authorization": "xxxxxxx"
            },
            useQuerystring: true,
            json: {
                "data": {
                    "resource_type": "lead",
                    "resource_id": response.body.data.id,
                    "content": req.body.message
                },
                "meta": {
                    "type": "note"
                }
            }
        };
        request(options, function(error, response, body) {});
    });
    var sha1 = require('sha1');
    var POST_data = {
        "email": req.body.mail,
        "list": "xxxxxxx",
        "state": "xxxxxxx"
    };
    POST_data = JSON.stringify(POST_data)
    var ApiKey = 'xxxxxxx',
        ApiSecret = 'xxxxxxx',
        GET_data = 'xxxxxxx';


    var myhex = sha1(ApiKey + GET_data + POST_data + ApiSecret);
    var xxxxxxxoptions = {
        uri: 'xxxxxxx',
        method: 'POST',
        headers: {
            "X-Rest-ApiKey": "xxxxxxx",
            "X-Rest-ApiSign": myhex,
            "Content-Type": "application/json"
        },
        useQuerystring: false,
        json: {
            "email": req.body.mail,
            "list": "xxxxxxx",
            "state": "xxxxxxx"
        }
    };
    request(xxxxxxxoptions, function(error, response, body) {});

Thx for trying help!

**Comment by RGBboy** [comment]
I'm guessing you have omitted some of your callbacks passed to request. You don't happen to accidentally call a method on res instead of response in one of those do you?

Other than that I would be interested in seeing the complete route function. E.g the `function (req, res, next) { ... }` where all this happens.

The only other thing that I think it could be is a previous matching route calling a sending method on the response object and calling next.

Try comment out line 255 and test if you get a response. If so your app is responding somewhere else.

**Comment by pagoad** [comment]
Thx. Now This problem happens only when I get spam.
