### ISSUE TITLE
Can't pass variable

### ISSUE THREAD

**Issue by kian93** [RGBboy/express-mailer#25]
It can't pass my variable to my ejs email template, my code:
```
var mailOptions = {
      to: 'newuser@gmail.com',
      subject: 'Hello',
      testProperty: 'testProperty'
    }
    app.mailer.send('email', mailOptions, function (err) {
      if (err) {
        // handle error
        console.log(err);
        res.send('There was an error sending the email');
        return;
      }
      res.send('Email Sent');
    });
```

my template code: 
```
<html>

	<head>
		<title>{{subject}}</title>
	</head>
	<body>
		{{testProperty}}
	</body>

</html>
```

**Comment by ajbraus** [comment]
+1

**Comment by RGBboy** [comment]
The only thing I can think is that you have not set up your [view engine for your express application] (http://expressjs.com/en/api.html#app.settings.table) to use ejs.

``` javascript
app.set('view engine', 'jade');
```

Have a look at the tests and see if you can get them working correctly. Then try change the view engine to use ejs.

**Comment by RGBboy** [comment]
Closing this for now. If this does not solve your problem feel free to reopen with further information.

**Comment by sgentile** [comment]
This is not working for me as well - subject comes through but not the testProperty.  (Your documentation also show 'subject' but not the use of testProperty inside the template itself)
