### ISSUE TITLE
Problem sending from a router

### ISSUE THREAD

**Issue by custa1200** [RGBboy/express-mailer#26]
I have cut out some of the code that is not helpful in my issue and only tried to include what I believe actually affect the problem.

In my app.js I have:
```
var express = require('express');
var mailer = require('express-mailer');
var app = express();

var routes = require('./routes/index');

mailer.extend(app, {
    from: 'no-reply@xxx.com',
    host: 'smtp.gmail.com', // hostname
    secureConnection: true, // use SSL
    port: 465, // port for secure SMTP
    transportMethod: 'SMTP', // default is SMTP. Accepts anything that nodemailer accepts
    auth: {
        user: 'xxx@gmail.com',
        pass: 'xxx'
    }
});
```

and in my index.js route file I have 

```
var express = require('express');
var router = express.Router();

router.post("/contact", function(req, res, next) {
    var contactName = req.body.name;
    var contactEmail = req.body.email;
    var contactMessage = req.body.message;

    app.mailer.send('email-request-sent', {
        to: contactEmail, // REQUIRED. This can be a comma delimited string just like a normal email to field.
        subject: 'Thankyou for you message to', // REQUIRED.
        otherProperty: contactMessage // All additional properties are also passed to the template as local variables.
    }, function(err) {
        if (err) {
            // handle error
            console.log(err);
            res.send('There was an error sending the email');
            return;
        }
        res.render("contact-success");
    });
});
```

but after I post my form I get the following error:

> TypeError: Cannot read property 'send' of undefined at /Users/custa/github/Portfolio/portfolioapp/routes/index.js:83:15

where 83:15 is 
```
app.mailer.send('email-request-sent', {
```

Not sure what I am doing wrong, I'm also pretty new to Express

**Comment by RGBboy** [comment]
It looks like the variable app is not defined within your routes/index.js file. Perhaps your should try using the mailer object via the res object:

``` javascript
res.mailer.send('email-request-sent', { ...
```

**Comment by ariestav** [comment]
@RGBboy Thank you for this suggestion.  It worked for my application.  Below is the code that is in my router.  My only suggestion is to include something like this as code example in your documentation.  My guess is that devs will likely implement express-mailer's methods in a route rather than in `app.js`.  Again, just a suggestion, and thank you for providing your comment.

```javascript
var express      = require('express');
var router       = express.Router();

router.get('/send', function(req, res, next) {

    console.log(req.body);

    res.mailer.send('../views/emails/generic', {
        to: 'somebody@gmail.com', // REQUIRED. This can be a comma delimited string just like a normal email to field.
        subject: 'Test Email from Express JS application', // REQUIRED.
        otherProperty: 'Other Property' // All additional properties are also passed to the template as local variables.
      }, function (err) {
        if (err) {
          // handle error
          console.log(err);
          res.send('There was an error sending the email');
          return;
        }
        res.send('Email Sent');
      });

});

**Comment by palgit** [comment]
I have used the similar code still getting following error : TypeError: Cannot read property 'send' of undefined at

**Comment by ariestav** [comment]
That likely means either res, or res.mailer are undefined.  Are you sure those objects exist and are defined when the route gets hit?

I think you still need to define mailer in app.js or whichever file is the root of the application.

**Comment by palgit** [comment]
yes its defined. Now that issue solved.  Now getting following 
 Error: Cannot find module 'jade'

**Comment by ariestav** [comment]
In your express app, you can use different templating engines.  I think jade changed to pug due to trademark issues.  Check out https://pugjs.org/api/getting-started.html for more information about that templating engine.

**Comment by palgit** [comment]
Thanks for the information. Let me try once.

**Comment by sinahedayati** [comment]
how to solve this error 

error : TypeError: Cannot read property 'send' of undefined at

**Comment by SaiCharanA** [comment]
@sinahedayati 
Need to explicity add it to your req, res objects

app.use(function (req, res, next){
    req.mailer = app.mailer;
    res.mailer = app.mailer;
    next();
});

app.use('/', require('./routes/index.js'));

**Comment by peprog** [comment]
> @sinahedayati
> Need to explicity add it to your req, res objects
> 
> app.use(function (req, res, next){
> req.mailer = app.mailer;
> res.mailer = app.mailer;
> next();
> });
> 
> app.use('/', require('./routes/index.js'));

Dude, I did this but still I get undefined of res.mailer
The only thing that is different is my routing system which I add routes directly in router.get();
How can I resolve this?
