### ISSUE TITLE
express mailer styles not getting applied

### ISSUE THREAD

**Issue by aditya61085** [RGBboy/express-mailer#28]
This is my function below. I am getting email but styles are not getting applied. Would like your help to review:

'use strict'
var express = require('express');
var mailer = require('express-mailer');
var emailSettings = require('./emailSettings');
var _ = require('lodash');
var bodyParser = require('body-parser');

var emailFunctions = {
   sendEmail : function(mailObj, req) {
        console.log("In emailFunctions.sendEmail");
        var app = express();
        mailer.extend(app, emailSettings);

        mailObj.host = req.headers.host;
        var emailContent = this.getEmailContent(mailObj);
        console.log("emailContent", emailContent);

        app.set('views', __dirname + '/views');
        app.engine('html', require('ejs').renderFile);
        app.set('view engine', 'html');

        app.mailer.send(
            {
                template: emailContent.template, // REQUIRED
                bcc: emailContent.bcc,
                from: emailContent.from
            },
            {
                to: emailContent.to,
                subject: emailContent.subject,
                mailData: emailContent
            },
            function(err) {
                console.log("After sending mail :::");
                if (err) {
                    console.log('Sending Mail Failed!');
                    console.log(err);
                    return false;
                };
                return true;
            }
        );
    }

And the email template file is:

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width; " />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><%= mailData.title %></title>
    <link href="styles.css" media="all" rel="stylesheet" type="text/css" />

    <style type="text/css">
/* -------------------------------------
    GLOBAL
    A very basic CSS reset
------------------------------------- */
* {
    margin: 0;
    padding: 0;
    font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
    box-sizing: border-box;
    font-size: 14px;
}

img {
    max-width: 100%;
}

body {
    -webkit-font-smoothing: antialiased;
    -webkit-text-size-adjust: none;
    width: 100% !important;
    height: 100%;
    line-height: 1.6;
}

.btn-primary {
    text-decoration: none;
    color: #FFF;
    background-color: #1ab394;
    border: solid #1ab394;
    border-width: 5px 10px;
    line-height: 2;
    font-weight: bold;
    text-align: center;
    cursor: pointer;
    display: inline-block;
    border-radius: 5px;
    text-transform: capitalize;
}
</style>
</head>
<body>
< d iv class="body-wrap" >

                                  < a class="btn-primary">Confirm Email Address< /a >

< /div>
</body>
</html>

The btn-primary is not getting applied in web clients like gmail etc.

**Comment by RGBboy** [comment]
Go have a look at how to style emails. It is a very different landscape to normal webpage styling. I'm pretty sure gmail strips out any css class for security reasons. You must use inline styles in order to style. It is explained here: https://litmus.com/blog/understanding-gmail-and-css-part-1
