### ISSUE TITLE
Can I send email from two different email addresses? (with two instance of express-mailer)

### ISSUE THREAD

**Issue by fransiskapw** [RGBboy/express-mailer#29]
I need to create app that can send email from two different email addresses. Can I do this with express mailer? I tried to create two instance of express-mailer so each will use different option thus can use different email address, but it gave me error: "Application already has been extended with Express-Mailer!"

**Comment by RGBboy** [comment]
I don't think so, not easily at least. This project is pretty dead to be honest. You could fork it and add that feature. Honestly though, if it were me I would just use the underlying `nodemailer` library directly.

**Comment by fransiskapw** [comment]
Thanks for the candor feedback! I end up using nodemailer directly with jade renderer
