### ISSUE TITLE
Sent From is displaying wrong email

### ISSUE THREAD

**Issue by parthpatwala** [RGBboy/express-mailer#43]
This is my email config file
```
{
    from: 'John Doe <info@no-replay.com>',
    host: 'smtp.gmail.com',
    secureConnection: false,
    port: 587, 
    transportMethod: 'SMTP', 
    auth: {
        user: 'xxx@gmail.com',
        pass: 'xxxxxxx'
    }
}
```
Now when i send an email everything works but instead of showing From : 'John Doe <info@no-replay.com>' it is showing me From: 'John Doe xxx@gmail.com'. I also passed from key in mailer function but it is still not updating. 
Is there any way to set From email forcefully to show it email?

**Comment by ddemid** [comment]
@parthpatwala you can remove `from` from the config and use the one in `.send`
