### ISSUE TITLE
[question] otherPropery's first parameter

### ISSUE THREAD

**Issue by kuil09** [RGBboy/express-mailer#45]
Hi, I'm new Node.js. I searched web for email send, and I found yours.
In my situation is otherProperty's first parameter not working properly

```
app.mailer.send('email', {
    to: 'text@test.co.kr',
    subject: '[SYSTEM] TEST',
    otherProperty: '', thisMonth, thisMonthLastDate, // I can access thisMonth, thisMonthLastDate
    otherProperty:  thisMonth, thisMonthLastDate, // I can't access thisMonth, What happend here?
},
```

What am I missed?
And thank you to share your nice work. :)

**Comment by dgramma** [comment]
I'm sure you figured this out by now, but you set the name you would like for the property, so you need to change your instance of `otherProperty` to whatever you would like the variable name to be. It didn't work in the second case because you already used that property name above.
